create type "public"."carrier_code" as enum ('AAA', 'ABF', 'AVR', 'CEN', 'ESTES', 'FEF', 'OLD', 'R&L', 'SAIA', 'SEF', 'T-FORCE', 'WARD', 'XPO');

create type "public"."dock_door_status" as enum ('out_of_service', 'available', 'loading');

create sequence "public"."callins_id_seq";

create sequence "public"."liveloads_id_seq";

create table "public"."btx" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "submitted_by" uuid default auth.uid(),
    "type" text not null,
    "control_no" text not null,
    "wave_no" text,
    "tracking_no" text,
    "pallets" integer not null default 0,
    "cartons" integer not null default 0,
    "length_in" numeric(10,2),
    "width_in" numeric(10,2),
    "height_in" numeric(10,2),
    "qty" integer not null default 1,
    "volume_in3" numeric(18,2) generated always as (((length_in * width_in) * height_in)) stored,
    "submission_id" uuid,
    "item_type" text
);


alter table "public"."btx" enable row level security;

create table "public"."callins" (
    "id" bigint not null default nextval('callins_id_seq'::regclass),
    "submitted_by" uuid not null,
    "submitted_at" timestamp with time zone not null default now(),
    "carrier" carrier_code not null,
    "ready_time" time without time zone not null,
    "trailer_no" text not null,
    "dock" smallint not null,
    "notes" text,
    "submitted_date_est" date generated always as (((submitted_at AT TIME ZONE 'America/New_York'::text))::date) stored
);


alter table "public"."callins" enable row level security;

create table "public"."changeovers" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "department" text not null,
    "submitted_by" uuid default auth.uid(),
    "submitted_by_name" text,
    "original_ship_via" text not null,
    "new_ship_via" text not null,
    "control_no" text not null,
    "wave_no" text,
    "pallets" integer not null default 0,
    "cartons" integer not null default 0,
    "so_no" text,
    "delivery_no" text,
    "reason_for_change" text
);


alter table "public"."changeovers" enable row level security;

create table "public"."dimensions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "control_no" text,
    "length_in" numeric(10,2),
    "width_in" numeric(10,2),
    "height_in" numeric(10,2),
    "qty" integer not null default 1,
    "submitted_by" uuid not null default auth.uid(),
    "updated_at" timestamp with time zone not null default now(),
    "control_no_norm" text,
    "volume_in3" numeric(18,2) generated always as (((length_in * width_in) * height_in)) stored,
    "ship_via" text,
    "skids" integer not null default 0,
    "cartons" integer default 0,
    "wave_no" text
);


alter table "public"."dimensions" enable row level security;

create table "public"."dock_doors" (
    "id" bigint generated always as identity not null,
    "door_number" integer not null,
    "label" text generated always as (('Dock Door '::text || door_number)) stored,
    "status" dock_door_status not null default 'available'::dock_door_status,
    "carrier" text,
    "trailer" text,
    "updated_by" uuid,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


create table "public"."line_counts" (
    "id" uuid not null default gen_random_uuid(),
    "count_date" date not null,
    "time_period" text not null,
    "preferreds" integer not null default 0,
    "parcels" integer not null default 0,
    "ltl" integer not null default 0,
    "total" integer not null default 0,
    "submitted_by" uuid default auth.uid(),
    "submitted_at" timestamp with time zone not null default now()
);


alter table "public"."line_counts" enable row level security;

create table "public"."liveloads" (
    "id" bigint not null default nextval('liveloads_id_seq'::regclass),
    "carrier" text not null,
    "ps_count" integer not null default 0,
    "avd_count" integer not null default 0,
    "raceway_pallets" integer not null default 0,
    "fitting_pallets" integer not null default 0,
    "cartons_95" integer not null default 0,
    "total_pallets" integer not null default 0,
    "total_cartons" integer not null default 0,
    "submitted_by" uuid not null,
    "created_time" timestamp with time zone not null default now()
);


alter table "public"."liveloads" enable row level security;

create table "public"."profiles" (
    "id" uuid not null,
    "full_name" text,
    "role" text not null default 'general'::text,
    "avatar_url" text,
    "created_at" timestamp with time zone default now(),
    "approved" boolean not null default false,
    "is_approved" boolean default false
);


alter table "public"."profiles" enable row level security;

create table "public"."truckloads" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "submitted_by" uuid default auth.uid(),
    "pickup_date" date not null,
    "department" text not null,
    "ship_via" text not null,
    "po_numbers" text[] not null default '{}'::text[],
    "control_numbers" text[] not null default '{}'::text[],
    "wave_no" text,
    "company_name" text,
    "destination" text,
    "pieces" integer not null default 0,
    "weight_lbs" numeric(12,2) default 0,
    "is_completed" boolean not null default false,
    "completed_at" timestamp with time zone,
    "notes" text,
    "is_preload" boolean not null default false
);


alter table "public"."truckloads" enable row level security;

alter sequence "public"."callins_id_seq" owned by "public"."callins"."id";

alter sequence "public"."liveloads_id_seq" owned by "public"."liveloads"."id";

CREATE INDEX btx_control_no_idx ON public.btx USING btree (control_no);

CREATE INDEX btx_control_wave_idx ON public.btx USING btree (control_no, wave_no);

CREATE INDEX btx_created_at_idx ON public.btx USING btree (created_at DESC);

CREATE UNIQUE INDEX btx_pkey ON public.btx USING btree (id);

CREATE INDEX btx_submission_idx ON public.btx USING btree (submission_id);

CREATE INDEX btx_tracking_idx ON public.btx USING btree (tracking_no);

CREATE INDEX btx_type_idx ON public.btx USING btree (type);

CREATE INDEX btx_wave_no_idx ON public.btx USING btree (wave_no);

CREATE INDEX callins_carrier_idx ON public.callins USING btree (carrier);

CREATE UNIQUE INDEX callins_pkey ON public.callins USING btree (id);

CREATE INDEX callins_submitted_at_desc_idx ON public.callins USING btree (submitted_at DESC);

CREATE INDEX callins_submitted_date_est_idx ON public.callins USING btree (submitted_date_est);

CREATE INDEX changeovers_control_no_idx ON public.changeovers USING btree (control_no);

CREATE INDEX changeovers_created_at_idx ON public.changeovers USING btree (created_at DESC);

CREATE INDEX changeovers_dept_idx ON public.changeovers USING btree (department);

CREATE UNIQUE INDEX changeovers_pkey ON public.changeovers USING btree (id);

CREATE INDEX changeovers_wave_idx ON public.changeovers USING btree (wave_no);

CREATE INDEX dimensions_control_no_idx ON public.dimensions USING btree (control_no);

CREATE INDEX dimensions_created_at_idx ON public.dimensions USING btree (created_at DESC);

CREATE UNIQUE INDEX dimensions_pkey ON public.dimensions USING btree (id);

CREATE INDEX dimensions_wave_no_idx ON public.dimensions USING btree (wave_no);

CREATE INDEX dock_doors_door_number_idx ON public.dock_doors USING btree (door_number);

CREATE UNIQUE INDEX dock_doors_door_number_key ON public.dock_doors USING btree (door_number);

CREATE UNIQUE INDEX dock_doors_pkey ON public.dock_doors USING btree (id);

CREATE INDEX dock_doors_status_idx ON public.dock_doors USING btree (status);

CREATE INDEX line_counts_date_idx ON public.line_counts USING btree (count_date DESC);

CREATE UNIQUE INDEX line_counts_pkey ON public.line_counts USING btree (id);

CREATE INDEX line_counts_submitted_at_idx ON public.line_counts USING btree (submitted_at DESC);

CREATE INDEX line_counts_time_period_idx ON public.line_counts USING btree (time_period);

CREATE UNIQUE INDEX line_counts_unique_period ON public.line_counts USING btree (count_date, time_period);

CREATE UNIQUE INDEX liveloads_pkey ON public.liveloads USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE INDEX truckloads_completed_at_idx ON public.truckloads USING btree (completed_at DESC);

CREATE INDEX truckloads_created_at_idx ON public.truckloads USING btree (created_at DESC);

CREATE INDEX truckloads_department_idx ON public.truckloads USING btree (department);

CREATE INDEX truckloads_is_preload_idx ON public.truckloads USING btree (is_preload) WHERE is_preload;

CREATE INDEX truckloads_pickup_date_idx ON public.truckloads USING btree (pickup_date);

CREATE UNIQUE INDEX truckloads_pkey ON public.truckloads USING btree (id);

CREATE INDEX truckloads_ship_via_idx ON public.truckloads USING btree (ship_via);

alter table "public"."btx" add constraint "btx_pkey" PRIMARY KEY using index "btx_pkey";

alter table "public"."callins" add constraint "callins_pkey" PRIMARY KEY using index "callins_pkey";

alter table "public"."changeovers" add constraint "changeovers_pkey" PRIMARY KEY using index "changeovers_pkey";

alter table "public"."dimensions" add constraint "dimensions_pkey" PRIMARY KEY using index "dimensions_pkey";

alter table "public"."dock_doors" add constraint "dock_doors_pkey" PRIMARY KEY using index "dock_doors_pkey";

alter table "public"."line_counts" add constraint "line_counts_pkey" PRIMARY KEY using index "line_counts_pkey";

alter table "public"."liveloads" add constraint "liveloads_pkey" PRIMARY KEY using index "liveloads_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."truckloads" add constraint "truckloads_pkey" PRIMARY KEY using index "truckloads_pkey";

alter table "public"."btx" add constraint "btx_cartons_check" CHECK ((cartons >= 0)) not valid;

alter table "public"."btx" validate constraint "btx_cartons_check";

alter table "public"."btx" add constraint "btx_control_digits" CHECK ((control_no ~ '^[0-9]{1,20}$'::text)) not valid;

alter table "public"."btx" validate constraint "btx_control_digits";

alter table "public"."btx" add constraint "btx_height_in_check" CHECK ((height_in > (0)::numeric)) not valid;

alter table "public"."btx" validate constraint "btx_height_in_check";

alter table "public"."btx" add constraint "btx_length_in_check" CHECK ((length_in > (0)::numeric)) not valid;

alter table "public"."btx" validate constraint "btx_length_in_check";

alter table "public"."btx" add constraint "btx_pallets_check" CHECK ((pallets >= 0)) not valid;

alter table "public"."btx" validate constraint "btx_pallets_check";

alter table "public"."btx" add constraint "btx_qty_check" CHECK ((qty > 0)) not valid;

alter table "public"."btx" validate constraint "btx_qty_check";

alter table "public"."btx" add constraint "btx_submitted_by_fkey" FOREIGN KEY (submitted_by) REFERENCES profiles(id) ON DELETE SET NULL not valid;

alter table "public"."btx" validate constraint "btx_submitted_by_fkey";

alter table "public"."btx" add constraint "btx_width_in_check" CHECK ((width_in > (0)::numeric)) not valid;

alter table "public"."btx" validate constraint "btx_width_in_check";

alter table "public"."callins" add constraint "callins_dock_check" CHECK (((dock >= 0) AND (dock <= 999))) not valid;

alter table "public"."callins" validate constraint "callins_dock_check";

alter table "public"."callins" add constraint "callins_submitted_by_fkey" FOREIGN KEY (submitted_by) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."callins" validate constraint "callins_submitted_by_fkey";

alter table "public"."callins" add constraint "callins_submitted_by_profiles_fkey" FOREIGN KEY (submitted_by) REFERENCES profiles(id) ON DELETE SET NULL not valid;

alter table "public"."callins" validate constraint "callins_submitted_by_profiles_fkey";

alter table "public"."callins" add constraint "callins_trailer_no_check" CHECK ((length(trailer_no) <= 32)) not valid;

alter table "public"."callins" validate constraint "callins_trailer_no_check";

alter table "public"."changeovers" add constraint "changeovers_cartons_check" CHECK ((cartons >= 0)) not valid;

alter table "public"."changeovers" validate constraint "changeovers_cartons_check";

alter table "public"."changeovers" add constraint "changeovers_control_digits" CHECK ((control_no ~ '^[0-9]{1,20}$'::text)) not valid;

alter table "public"."changeovers" validate constraint "changeovers_control_digits";

alter table "public"."changeovers" add constraint "changeovers_pallets_check" CHECK ((pallets >= 0)) not valid;

alter table "public"."changeovers" validate constraint "changeovers_pallets_check";

alter table "public"."dimensions" add constraint "dimensions_control_no_fmt" CHECK (((control_no IS NULL) OR ((length(regexp_replace(control_no, '\D'::text, ''::text, 'g'::text)) >= 1) AND (length(regexp_replace(control_no, '\D'::text, ''::text, 'g'::text)) <= 12)))) not valid;

alter table "public"."dimensions" validate constraint "dimensions_control_no_fmt";

alter table "public"."dimensions" add constraint "dimensions_height_in_check" CHECK ((height_in > (0)::numeric)) not valid;

alter table "public"."dimensions" validate constraint "dimensions_height_in_check";

alter table "public"."dimensions" add constraint "dimensions_length_in_check" CHECK ((length_in > (0)::numeric)) not valid;

alter table "public"."dimensions" validate constraint "dimensions_length_in_check";

alter table "public"."dimensions" add constraint "dimensions_qty_check" CHECK ((qty > 0)) not valid;

alter table "public"."dimensions" validate constraint "dimensions_qty_check";

alter table "public"."dimensions" add constraint "dimensions_submitted_by_fkey" FOREIGN KEY (submitted_by) REFERENCES profiles(id) ON DELETE SET NULL not valid;

alter table "public"."dimensions" validate constraint "dimensions_submitted_by_fkey";

alter table "public"."dimensions" add constraint "dimensions_wave_no_fmt" CHECK (((wave_no IS NULL) OR (wave_no ~ '^[A-Za-z0-9_-]+$'::text))) not valid;

alter table "public"."dimensions" validate constraint "dimensions_wave_no_fmt";

alter table "public"."dimensions" add constraint "dimensions_width_in_check" CHECK ((width_in > (0)::numeric)) not valid;

alter table "public"."dimensions" validate constraint "dimensions_width_in_check";

alter table "public"."dock_doors" add constraint "chk_carrier_trim" CHECK (((carrier IS NULL) OR (btrim(carrier) <> ''::text))) not valid;

alter table "public"."dock_doors" validate constraint "chk_carrier_trim";

alter table "public"."dock_doors" add constraint "chk_trailer_trim" CHECK (((trailer IS NULL) OR (btrim(trailer) <> ''::text))) not valid;

alter table "public"."dock_doors" validate constraint "chk_trailer_trim";

alter table "public"."dock_doors" add constraint "dock_doors_door_number_key" UNIQUE using index "dock_doors_door_number_key";

alter table "public"."dock_doors" add constraint "dock_doors_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."dock_doors" validate constraint "dock_doors_updated_by_fkey";

alter table "public"."line_counts" add constraint "line_counts_ltl_check" CHECK ((ltl >= 0)) not valid;

alter table "public"."line_counts" validate constraint "line_counts_ltl_check";

alter table "public"."line_counts" add constraint "line_counts_parcels_check" CHECK ((parcels >= 0)) not valid;

alter table "public"."line_counts" validate constraint "line_counts_parcels_check";

alter table "public"."line_counts" add constraint "line_counts_preferreds_check" CHECK ((preferreds >= 0)) not valid;

alter table "public"."line_counts" validate constraint "line_counts_preferreds_check";

alter table "public"."line_counts" add constraint "line_counts_submitted_by_profiles_fkey" FOREIGN KEY (submitted_by) REFERENCES profiles(id) not valid;

alter table "public"."line_counts" validate constraint "line_counts_submitted_by_profiles_fkey";

alter table "public"."line_counts" add constraint "line_counts_unique_period" UNIQUE using index "line_counts_unique_period";

alter table "public"."liveloads" add constraint "liveloads_avd_count_check" CHECK ((avd_count >= 0)) not valid;

alter table "public"."liveloads" validate constraint "liveloads_avd_count_check";

alter table "public"."liveloads" add constraint "liveloads_cartons_95_check" CHECK ((cartons_95 >= 0)) not valid;

alter table "public"."liveloads" validate constraint "liveloads_cartons_95_check";

alter table "public"."liveloads" add constraint "liveloads_fitting_pallets_check" CHECK ((fitting_pallets >= 0)) not valid;

alter table "public"."liveloads" validate constraint "liveloads_fitting_pallets_check";

alter table "public"."liveloads" add constraint "liveloads_ps_count_check" CHECK ((ps_count >= 0)) not valid;

alter table "public"."liveloads" validate constraint "liveloads_ps_count_check";

alter table "public"."liveloads" add constraint "liveloads_raceway_pallets_check" CHECK ((raceway_pallets >= 0)) not valid;

alter table "public"."liveloads" validate constraint "liveloads_raceway_pallets_check";

alter table "public"."liveloads" add constraint "liveloads_submitted_by_fkey" FOREIGN KEY (submitted_by) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."liveloads" validate constraint "liveloads_submitted_by_fkey";

alter table "public"."liveloads" add constraint "liveloads_submitted_by_profiles_fkey" FOREIGN KEY (submitted_by) REFERENCES profiles(id) ON DELETE SET NULL not valid;

alter table "public"."liveloads" validate constraint "liveloads_submitted_by_profiles_fkey";

alter table "public"."liveloads" add constraint "liveloads_total_cartons_check" CHECK ((total_cartons >= 0)) not valid;

alter table "public"."liveloads" validate constraint "liveloads_total_cartons_check";

alter table "public"."liveloads" add constraint "liveloads_total_pallets_check" CHECK ((total_pallets >= 0)) not valid;

alter table "public"."liveloads" validate constraint "liveloads_total_pallets_check";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."truckloads" add constraint "truckloads_pieces_check" CHECK ((pieces >= 0)) not valid;

alter table "public"."truckloads" validate constraint "truckloads_pieces_check";

alter table "public"."truckloads" add constraint "truckloads_weight_lbs_check" CHECK ((weight_lbs >= (0)::numeric)) not valid;

alter table "public"."truckloads" validate constraint "truckloads_weight_lbs_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name',''), 'general')
  on conflict (id) do nothing;
  return new;
end; $function$
;

CREATE OR REPLACE FUNCTION public.set_submitted_by_name()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
  v_name text;
begin
  if new.submitted_by is null then
    return new;
  end if;

  select coalesce(
           p.full_name,
           au.raw_user_meta_data->>'full_name',
           au.raw_user_meta_data->>'username',
           split_part(au.email, '@', 1)
         )
    into v_name
  from auth.users au
  left join public.profiles p on p.id = au.id
  where au.id = new.submitted_by;

  new.submitted_by_name := v_name;
  return new;
end
$function$
;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END $function$
;

CREATE OR REPLACE FUNCTION public.set_updated_meta()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  new.updated_at := now();
  if auth.uid() is not null then new.updated_by := auth.uid(); end if;
  return new;
end $function$
;

create or replace view "public"."v_btx" as  SELECT b.id,
    b.created_at,
    COALESCE((to_jsonb(p.*) ->> 'username'::text), (to_jsonb(p.*) ->> 'full_name'::text), NULLIF(TRIM(BOTH FROM concat_ws(' '::text, (to_jsonb(p.*) ->> 'first_name'::text), (to_jsonb(p.*) ->> 'last_name'::text))), ''::text), (to_jsonb(p.*) ->> 'email'::text), (b.submitted_by)::text) AS user_display,
    b.type,
    b.control_no,
    b.wave_no,
    b.pallets,
    b.cartons,
    b.length_in,
    b.width_in,
    b.height_in,
    b.qty,
    b.volume_in3,
    b.submission_id,
    b.submitted_by
   FROM (btx b
     LEFT JOIN profiles p ON ((p.id = b.submitted_by)));


create or replace view "public"."v_btx_summary" as  WITH latest AS (
         SELECT DISTINCT ON (b_1.submission_id) b_1.submission_id,
            b_1.created_at,
            b_1.type,
            b_1.control_no,
            b_1.wave_no,
            b_1.submitted_by
           FROM btx b_1
          WHERE (b_1.submission_id IS NOT NULL)
          ORDER BY b_1.submission_id, b_1.created_at DESC
        )
 SELECT l.created_at,
    COALESCE((to_jsonb(p.*) ->> 'username'::text), (to_jsonb(p.*) ->> 'full_name'::text), NULLIF(TRIM(BOTH FROM concat_ws(' '::text, (to_jsonb(p.*) ->> 'first_name'::text), (to_jsonb(p.*) ->> 'last_name'::text))), ''::text), (to_jsonb(p.*) ->> 'email'::text), (l.submitted_by)::text) AS user_display,
    l.type,
    l.control_no,
    l.wave_no,
    COALESCE(sum(b.pallets), (0)::bigint) AS pallets,
    COALESCE(sum(b.cartons), (0)::bigint) AS cartons,
    l.submission_id
   FROM ((latest l
     JOIN btx b ON ((b.submission_id = l.submission_id)))
     LEFT JOIN profiles p ON ((p.id = l.submitted_by)))
  GROUP BY l.created_at, l.type, l.control_no, l.wave_no, l.submitted_by, p.id, l.submission_id;


create or replace view "public"."v_callins" as  SELECT c.id,
    c.submitted_by,
    c.submitted_at,
    c.carrier,
    c.ready_time,
    c.trailer_no,
    c.dock,
    c.notes,
    c.submitted_date_est,
    COALESCE(p.full_name, (au.raw_user_meta_data ->> 'full_name'::text), (au.raw_user_meta_data ->> 'username'::text), split_part((au.email)::text, '@'::text, 1)) AS user_display
   FROM ((callins c
     LEFT JOIN profiles p ON ((p.id = c.submitted_by)))
     LEFT JOIN auth.users au ON ((au.id = c.submitted_by)));


create or replace view "public"."v_changeovers" as  SELECT c.id,
    c.created_at,
    c.department,
    COALESCE((to_jsonb(p.*) ->> 'username'::text), (to_jsonb(p.*) ->> 'full_name'::text), NULLIF(TRIM(BOTH FROM concat_ws(' '::text, (to_jsonb(p.*) ->> 'first_name'::text), (to_jsonb(p.*) ->> 'last_name'::text))), ''::text), (to_jsonb(p.*) ->> 'email'::text), (c.submitted_by)::text) AS user_display,
    c.original_ship_via,
    c.new_ship_via,
    c.control_no,
    c.wave_no,
    c.pallets,
    c.cartons,
    c.so_no,
    c.delivery_no,
    c.reason_for_change,
    c.submitted_by
   FROM (changeovers c
     LEFT JOIN profiles p ON ((p.id = c.submitted_by)));


create or replace view "public"."v_dimensions" as  SELECT d.id,
    d.created_at,
    d.control_no,
    d.wave_no,
    d.ship_via,
    d.skids,
    d.cartons,
    d.length_in,
    d.width_in,
    d.height_in,
    d.qty,
    d.volume_in3,
    d.submitted_by,
    COALESCE((to_jsonb(p.*) ->> 'username'::text), (to_jsonb(p.*) ->> 'full_name'::text), NULLIF(TRIM(BOTH FROM concat_ws(' '::text, (to_jsonb(p.*) ->> 'first_name'::text), (to_jsonb(p.*) ->> 'last_name'::text))), ''::text), (to_jsonb(p.*) ->> 'email'::text), (d.submitted_by)::text) AS user_display
   FROM (dimensions d
     LEFT JOIN profiles p ON ((p.id = d.submitted_by)));


create or replace view "public"."v_dimensions_summary" as  WITH ranked AS (
         SELECT d.id,
            d.created_at,
            d.control_no,
            d.length_in,
            d.width_in,
            d.height_in,
            d.qty,
            d.submitted_by,
            d.updated_at,
            d.control_no_norm,
            d.volume_in3,
            d.ship_via,
            d.skids,
            d.cartons,
            d.wave_no,
            row_number() OVER (PARTITION BY d.control_no ORDER BY d.created_at DESC, d.id DESC) AS rn
           FROM dimensions d
        )
 SELECT r.created_at,
    COALESCE((to_jsonb(p.*) ->> 'username'::text), (to_jsonb(p.*) ->> 'full_name'::text), NULLIF(TRIM(BOTH FROM concat_ws(' '::text, (to_jsonb(p.*) ->> 'first_name'::text), (to_jsonb(p.*) ->> 'last_name'::text))), ''::text), (to_jsonb(p.*) ->> 'email'::text), (r.submitted_by)::text) AS user_display,
    r.control_no,
    r.wave_no,
    r.ship_via,
    COALESCE(r.skids, 0) AS skids,
    COALESCE(r.cartons, 0) AS cartons
   FROM (ranked r
     LEFT JOIN profiles p ON ((p.id = r.submitted_by)))
  WHERE (r.rn = 1);


create or replace view "public"."v_line_counts" as  SELECT lc.id,
    lc.count_date,
    lc.time_period,
    lc.preferreds,
    lc.parcels,
    lc.ltl,
    lc.total,
    COALESCE(p.full_name, (au.raw_user_meta_data ->> 'full_name'::text), (au.raw_user_meta_data ->> 'username'::text), split_part((au.email)::text, '@'::text, 1)) AS user_display,
    lc.submitted_at,
    lc.submitted_by
   FROM ((line_counts lc
     LEFT JOIN profiles p ON ((p.id = lc.submitted_by)))
     LEFT JOIN auth.users au ON ((au.id = lc.submitted_by)));


create or replace view "public"."v_truckloads" as  SELECT t.id,
    t.created_at,
    t.pickup_date,
    t.department,
    t.ship_via,
    t.po_numbers,
    t.control_numbers,
    t.wave_no,
    t.company_name,
    t.destination,
    t.pieces,
    t.weight_lbs,
    t.is_completed,
    t.completed_at,
    COALESCE(p.full_name, (au.raw_user_meta_data ->> 'full_name'::text), (au.raw_user_meta_data ->> 'username'::text), split_part((au.email)::text, '@'::text, 1)) AS user_display,
    t.submitted_by,
    t.is_preload
   FROM ((truckloads t
     LEFT JOIN profiles p ON ((p.id = t.submitted_by)))
     LEFT JOIN auth.users au ON ((au.id = t.submitted_by)));


create policy "Admin can read all data"
on "public"."btx"
as permissive
for select
to service_role
using (true);


create policy "btx_delete_self"
on "public"."btx"
as permissive
for delete
to public
using ((submitted_by = auth.uid()));


create policy "btx_insert_self"
on "public"."btx"
as permissive
for insert
to public
with check ((submitted_by = auth.uid()));


create policy "btx_select_all"
on "public"."btx"
as permissive
for select
to public
using (true);


create policy "btx_update_self"
on "public"."btx"
as permissive
for update
to public
using ((submitted_by = auth.uid()))
with check ((submitted_by = auth.uid()));


create policy "delete: owner"
on "public"."btx"
as permissive
for delete
to authenticated
using ((submitted_by = auth.uid()));


create policy "insert: self"
on "public"."btx"
as permissive
for insert
to authenticated
with check ((submitted_by = auth.uid()));


create policy "select: authed"
on "public"."btx"
as permissive
for select
to authenticated
using (true);


create policy "update: owner"
on "public"."btx"
as permissive
for update
to authenticated
using ((submitted_by = auth.uid()))
with check ((submitted_by = auth.uid()));


create policy "Admin can read all data"
on "public"."callins"
as permissive
for select
to service_role
using (true);


create policy "callins_select_all"
on "public"."callins"
as permissive
for select
to public
using (true);


create policy "delete: owner"
on "public"."callins"
as permissive
for delete
to authenticated
using ((submitted_by = auth.uid()));


create policy "delete: self or admin"
on "public"."callins"
as permissive
for delete
to public
using (((submitted_by = auth.uid()) OR (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND (p.role = ANY (ARRAY['admin'::text, 'manager'::text])))))));


create policy "dimensions_select_all"
on "public"."callins"
as permissive
for select
to public
using (true);


create policy "insert: self & approved"
on "public"."callins"
as permissive
for insert
to public
with check (((submitted_by = auth.uid()) AND (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND p.approved)))));


create policy "insert: self"
on "public"."callins"
as permissive
for insert
to authenticated
with check ((submitted_by = auth.uid()));


create policy "select: approved only"
on "public"."callins"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND p.approved))));


create policy "select: authed"
on "public"."callins"
as permissive
for select
to authenticated
using (true);


create policy "update: owner"
on "public"."callins"
as permissive
for update
to authenticated
using ((submitted_by = auth.uid()))
with check ((submitted_by = auth.uid()));


create policy "update: self or admin"
on "public"."callins"
as permissive
for update
to public
using (((submitted_by = auth.uid()) OR (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND (p.role = ANY (ARRAY['admin'::text, 'manager'::text])))))));


create policy "Admin can read all data"
on "public"."changeovers"
as permissive
for select
to service_role
using (true);


create policy "delete: owner"
on "public"."changeovers"
as permissive
for delete
to authenticated
using ((submitted_by = auth.uid()));


create policy "insert: self"
on "public"."changeovers"
as permissive
for insert
to authenticated
with check ((submitted_by = auth.uid()));


create policy "select: authed"
on "public"."changeovers"
as permissive
for select
to authenticated
using (true);


create policy "update: owner"
on "public"."changeovers"
as permissive
for update
to authenticated
using ((submitted_by = auth.uid()))
with check ((submitted_by = auth.uid()));


create policy "Admin can read all data"
on "public"."dimensions"
as permissive
for select
to service_role
using (true);


create policy "dimensions_delete_self"
on "public"."dimensions"
as permissive
for delete
to public
using ((submitted_by = auth.uid()));


create policy "dimensions_insert_self"
on "public"."dimensions"
as permissive
for insert
to public
with check ((submitted_by = auth.uid()));


create policy "dimensions_select_all"
on "public"."dimensions"
as permissive
for select
to public
using (true);


create policy "dimensions_update_self"
on "public"."dimensions"
as permissive
for update
to public
using ((submitted_by = auth.uid()))
with check ((submitted_by = auth.uid()));


create policy "Admin can read all data"
on "public"."line_counts"
as permissive
for select
to service_role
using (true);


create policy "delete: owner"
on "public"."line_counts"
as permissive
for delete
to authenticated
using ((submitted_by = auth.uid()));


create policy "insert: self"
on "public"."line_counts"
as permissive
for insert
to authenticated
with check ((submitted_by = auth.uid()));


create policy "select: authed"
on "public"."line_counts"
as permissive
for select
to authenticated
using (true);


create policy "update: owner"
on "public"."line_counts"
as permissive
for update
to authenticated
using ((submitted_by = auth.uid()))
with check ((submitted_by = auth.uid()));


create policy "Admin can read all data"
on "public"."liveloads"
as permissive
for select
to service_role
using (true);


create policy "delete: self or admin"
on "public"."liveloads"
as permissive
for delete
to public
using (((submitted_by = auth.uid()) OR (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND (p.role = ANY (ARRAY['admin'::text, 'manager'::text])))))));


create policy "insert: self & approved"
on "public"."liveloads"
as permissive
for insert
to public
with check (((submitted_by = auth.uid()) AND (EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND p.approved)))));


create policy "select: approved only"
on "public"."liveloads"
as permissive
for select
to public
using ((EXISTS ( SELECT 1
   FROM profiles p
  WHERE ((p.id = auth.uid()) AND p.approved))));


create policy "Admin can read all data"
on "public"."profiles"
as permissive
for select
to service_role
using (true);


create policy "profiles select authed"
on "public"."profiles"
as permissive
for select
to authenticated
using (true);


create policy "profiles_select_all"
on "public"."profiles"
as permissive
for select
to public
using (true);


create policy "read own"
on "public"."profiles"
as permissive
for select
to public
using ((auth.uid() = id));


create policy "update own"
on "public"."profiles"
as permissive
for update
to public
using ((auth.uid() = id));


create policy "Admin can read all data"
on "public"."truckloads"
as permissive
for select
to service_role
using (true);


create policy "delete: owner"
on "public"."truckloads"
as permissive
for delete
to authenticated
using ((submitted_by = auth.uid()));


create policy "insert: self"
on "public"."truckloads"
as permissive
for insert
to authenticated
with check ((submitted_by = auth.uid()));


create policy "read truckloads (all auth)"
on "public"."truckloads"
as permissive
for select
to authenticated
using (true);


create policy "read_truckloads_all_auth"
on "public"."truckloads"
as permissive
for select
to authenticated
using (true);


create policy "select: authed"
on "public"."truckloads"
as permissive
for select
to authenticated
using (true);


create policy "update: owner"
on "public"."truckloads"
as permissive
for update
to authenticated
using ((submitted_by = auth.uid()))
with check ((submitted_by = auth.uid()));


CREATE TRIGGER t_set_updated_at_dimensions BEFORE UPDATE ON public.dimensions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON public.dock_doors FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_set_updated_meta BEFORE INSERT OR UPDATE ON public.dock_doors FOR EACH ROW EXECUTE FUNCTION set_updated_meta();


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();


